/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package View;


import Controler.GiangVienController;
import java.awt.HeadlessException;

/**
 *
 * @author Admin
 */
public class FrameGiangVien extends javax.swing.JFrame {

    /** Creates new form FrameGiangVien */
    public FrameGiangVien() {
        initComponents();
    }
    public String magv;
    public FrameGiangVien(String name,String ma) throws HeadlessException {
        initComponents();
        magv=ma;
        jlb_ma.setText(ma);
        jlbname.setText(name);
        GiangVienController controller=new GiangVienController(this, jbtxem, jbtnhap, jbtThongke, jbtout, jpnView);
        controller.setEvent();
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jlb_ma = new javax.swing.JLabel();
        jlbname = new javax.swing.JLabel();
        jpnView = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jbtout = new javax.swing.JButton();
        jbtThongke = new javax.swing.JButton();
        jbtxem = new javax.swing.JButton();
        jbtnhap = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtTip = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Welcome", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP));

        jLabel1.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel1.setText("Mã giảng viên:");
        jLabel1.setToolTipText("");

        jLabel2.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel2.setText("Tên giảng viên:");

        jlb_ma.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jlb_ma.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlb_ma.setText("jLabel1");

        jlbname.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jlbname.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlbname.setText("jLabel1");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jlb_ma, javax.swing.GroupLayout.DEFAULT_SIZE, 154, Short.MAX_VALUE)
                    .addComponent(jlbname, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jlb_ma))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlbname))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jpnViewLayout = new javax.swing.GroupLayout(jpnView);
        jpnView.setLayout(jpnViewLayout);
        jpnViewLayout.setHorizontalGroup(
            jpnViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 571, Short.MAX_VALUE)
        );
        jpnViewLayout.setVerticalGroup(
            jpnViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        jbtout.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jbtout.setText("Đăng xuất");
        jbtout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jbtoutMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jbtoutMouseExited(evt);
            }
        });
        jbtout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtoutActionPerformed(evt);
            }
        });

        jbtThongke.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jbtThongke.setText("Thống kê");
        jbtThongke.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jbtThongkeMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jbtThongkeMouseExited(evt);
            }
        });

        jbtxem.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jbtxem.setText("Bảng điểm");
        jbtxem.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jbtxemMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jbtxemMouseExited(evt);
            }
        });
        jbtxem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtxemActionPerformed(evt);
            }
        });

        jbtnhap.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jbtnhap.setText("Nhập điểm");
        jbtnhap.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jbtnhapMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jbtnhapMouseExited(evt);
            }
        });
        jbtnhap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnhapActionPerformed(evt);
            }
        });

        txtTip.setBackground(new java.awt.Color(204, 204, 204));
        txtTip.setColumns(20);
        txtTip.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        txtTip.setForeground(new java.awt.Color(0, 0, 0));
        txtTip.setRows(5);
        jScrollPane1.setViewportView(txtTip);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jbtxem, javax.swing.GroupLayout.DEFAULT_SIZE, 117, Short.MAX_VALUE)
                            .addComponent(jbtThongke, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jbtout, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jbtnhap, javax.swing.GroupLayout.DEFAULT_SIZE, 129, Short.MAX_VALUE))))
                .addGap(20, 20, 20))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jbtnhap, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jbtxem, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbtThongke)
                    .addComponent(jbtout))
                .addGap(26, 26, 26)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(23, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(jpnView, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(39, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(20, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jpnView, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(20, 20, 20))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbtxemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtxemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jbtxemActionPerformed

    private void jbtnhapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnhapActionPerformed
        // TODO add your handling code here:
        NhapDiem dk = new NhapDiem(magv);
        dk.setVisible(true);
        dk.setLocationRelativeTo(null);
    }//GEN-LAST:event_jbtnhapActionPerformed

    private void jbtoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtoutActionPerformed
        // TODO add your handling code here:
        this.dispose();
        LoginForm lg=new LoginForm();
        lg.setVisible(true);
    }//GEN-LAST:event_jbtoutActionPerformed

    private void jbtxemMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbtxemMouseEntered
        // TODO add your handling code here:
        txtTip.setText("Xem điểm và thông tin của các lớp");
    }//GEN-LAST:event_jbtxemMouseEntered

    private void jbtnhapMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbtnhapMouseEntered
        // TODO add your handling code here:
        txtTip.setText("Nhập, xuất điểm và thông tin của các\nlớp bằng file excel và tải lên cơ sở dữ\nliệu");
    }//GEN-LAST:event_jbtnhapMouseEntered

    private void jbtThongkeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbtThongkeMouseEntered
        // TODO add your handling code here:
        txtTip.setText("Xem điểm và thông tin của các lớp một\ncách trực quan thông qua biểu đổ và\nbảng thống kê dữ liệu");
    }//GEN-LAST:event_jbtThongkeMouseEntered

    private void jbtoutMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbtoutMouseEntered
        // TODO add your handling code here:
        txtTip.setText("Đăng xuất khỏi tài khoản và trở về\nmàn hình đăng nhập");
    }//GEN-LAST:event_jbtoutMouseEntered

    private void jbtxemMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbtxemMouseExited
        // TODO add your handling code here:
        txtTip.setText("");
    }//GEN-LAST:event_jbtxemMouseExited

    private void jbtnhapMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbtnhapMouseExited
        // TODO add your handling code here:
        txtTip.setText("");
    }//GEN-LAST:event_jbtnhapMouseExited

    private void jbtThongkeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbtThongkeMouseExited
        // TODO add your handling code here:
        txtTip.setText("");
    }//GEN-LAST:event_jbtThongkeMouseExited

    private void jbtoutMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbtoutMouseExited
        // TODO add your handling code here:
        txtTip.setText("");
    }//GEN-LAST:event_jbtoutMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrameGiangVien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrameGiangVien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrameGiangVien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrameGiangVien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrameGiangVien().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jbtThongke;
    private javax.swing.JButton jbtnhap;
    private javax.swing.JButton jbtout;
    private javax.swing.JButton jbtxem;
    private javax.swing.JLabel jlb_ma;
    private javax.swing.JLabel jlbname;
    private javax.swing.JPanel jpnView;
    private javax.swing.JTextArea txtTip;
    // End of variables declaration//GEN-END:variables

}
